layouts/partials/footer.html

https://github.com/gohugoio/hugoThemes/issues/881 is now resolved so footer can subsequently be updated.

Update footer Design URL from github.com to gohugo.io

---

static/js/index.js

Hi everyone,
i want to propose a solution for #20 . 
Currently, the activation of section headers is triggered when the container holding a section, i.e., page, crosses the upper window border. If the last section is small, like in the example site, the container never crosses the upper window border and thus the section header is not activated.
I would suggest to first check whether the footer is visible and if so, activate the last section heading.

Activate last section heading when approaching footer

---

layouts/index.html

If there is only a single page, the article element created will only have the `first` class, not the `last` class.
With this change the `last` class will also be added, which will remove the `post-after` element arrow that goes down into the footer.

Add both first and last classes when there is only one page

---

static/css/fonts.css

Hi!
When checking my website with Lighthouse, it gave me this:
>  Ensure text remains visible during webfont load 
> > Leverage the font-display CSS feature to ensure text is user-visible while webfonts are loading.
So i added this to all `@font-face`s <3
Didn't know what to do about forkawesome, because those are icons and you don't have a system fallback for those - so i left this

Add font-display: swap property to avoid invisible text

---

layouts/index.html

This change adds support for an "external" link in the main menu on the title page.
An external link can be added the keyword "external" to the front matter of a page, the value of the "external" key should be the external URL. 
An example page is here: https://evilrobots.ai/

external links - external links in main menu

---

layouts/index.html

SafeHTML signals to the go templating engine that the html in this string is considered safe and does not need to be escaped. This will allow me to add some additional markup to the title. In my case, I use an explicit <br/> tag to control the line break.

Add safeHTML to blog-title

---

.gitignore
assets/css/screen.css
assets/js/index.js
exampleSite/content/services.md

Change the way the template renders un-ordered lists according to recommendations at https://fontawesome.com/v5/docs/web/style/lists
Fixes #72

Use recommended style for fontawesom lists

---

assets/css/screen.css
assets/js/index.js
exampleSite/config.toml
layouts/index.html

Add invert Param to the config file. Add the 'odd' class to the post-holders and the 'even' class to the post-afters using Hugo IF statements instead of using JS. Marking invert = true in the config file flips which sections are marked odd and even.
Addresses #107.

Enable inverting homepage section styling

---

exampleSite/config.toml

Update base configuration docs about possibility to use plain HTML in your footer copyright variable.
https://github.com/zjedi/hugo-scroll/issues/120

#120 Update docs about plain HTML in footer

---

exampleSite/content/homepage/external.md

If one hits the button it should help you to find the project itself, instead of linking to GH base page.

Correct external link to lead to project itself

---

README.md
exampleSite/config.toml
layouts/partials/footer.html

Shows version information in the page's footer if configuration option 
`enableGitInfo` is set to `true`

#126: Provide option to show GitInfo in footer

---

README.md
exampleSite/content/homepage/credits.md
layouts/shortcodes/extlink.html

Add new parameter to external links to reference and print icons in front of external links.

Add ability to reference icons in external links

---

assets/css/variables.scss
assets/js/index.js
exampleSite/layouts/partials/custom_head.html

List icon configurable

---

assets/css/responsiveness.scss

Firstly, thank you very much for your work on this theme.
I have noticed that the blog logo is not scaled on smaller screens. It seems that the CSS-selector `#block-logo img` does not work, because the Element with the ID `block-logo` already is an img-Element and therefore is not referenced. This fix removes the `img` from the CSS-selector.

Fix blog-logo CSS selector in responsiveness.scss

---

assets/css/theme.scss
exampleSite/config.toml
exampleSite/content/homepage/license.md
exampleSite/content/license.md
layouts/partials/footer.html

The header menu might get a bit busy for pages with a lot of sections and links. So I thought it would be nice to add e.g. less important links to sub-pages you might be legally required to have, like license, imprint, copyright, etc. to the footer of the page.

add option to add links to the footer of the page

---

exampleSite/config.toml
exampleSite/content/homepage/contact.md
layouts/partials/footer.html
layouts/shortcodes/contact_list.html

Hi! 
This commits change the way contacts params are handled: instead of declaring them statically, they are declared as an array of tables in the TOML configuration file, then they are displayed in the two sections (homepage and footer) of the website through the {{ range }} statement.
This makes handling multiple contacts params easier and avoids the need of changing manually this two files:
- `layouts/partials/footer.html`;
- `exampleSite/content/homepage/contact.md`;
Of course this results in a breaking change for the template.
I think this new mechanism could be helpful when you need to add multiple contact options to the template.

Handle website contacts dynamically

---

assets/css/theme.scss
layouts/partials/footer.html

This commit changes the way contact icons are displayed in the footer: instead of using `<li>` tags which inherit a 30px left margin, they are now just simple `<a>` tags handled by flex to center them.
The new style rules are added to the `.icons` class in `assets/css/theme.scss`.
See #171 for context.

Center contact icons in the footer

---

exampleSite/config.toml
layouts/partials/footer.html

The `safeURL` function is required to insert URLs that are different than `http:`, `https:` and `mailto:` (e.g. `tel:`) through the Hugo templating system.
Additionally, an example about how to add new contacts is added in the `config.toml` of `exampleSite`.

Fix #173: `tel:` link is now handled correctly by Hugo

---

layouts/shortcodes/contact_list.html

Solves the issue for contact section combined with #174.
Sorry for the mess, I was in a hurry to solve the bug.

Fix #173: handle `tel:` link correctly also in contact section

---

exampleSite/config.toml
layouts/index.html

This pull request aims to add support to markdown emojis in the theme.
With the current version, adding emoticons with the markdown shortcodes ends with them not rendered in the web page. 
Adding `enableEmoji = true` in `config.toml` is a starting point but you can't insert emoticons in sections titles because they are rendered separately, thus also the `emojify` function is required (see [docs](https://gohugo.io/functions/transform/emojify/) for further reference) in the `index.html` file. 
With these two updates, the final result is the following:

Add support to markdown emojis

---

layouts/_default/single.html

Previously, the css of `blog-logo` was applied to the back button on single pages. This led to problems if the title required two lines:
With a unique id this is resolved:

Dedicated page - back button visual fix

---

layouts/_default/baseof.html

I have a site that uses this theme, and I wanted to verify my ownership of it so I could use Google's search console. Google supplied a custom `meta` tag so I put it into `layouts/partials/custom_head.html`; however, I still failed Google's validation. Then, I realized that the output of `layouts/partials/head.html` is not wrapped in <head></head> tags.
Once I added wrapped the output of head.html in `<head>` and `</head>`, I was able to verify my site.

Wrap meta information in <HEAD> tags

---

layouts/index.html

[W3 validator](https://validator.w3.org/) has an issue with `<icon>` tag inside of `<a>` likely because it's not a known HTML tag. Simply changing to an `<i>` tag removes the error
Work for #195

Wrap fork-awesome in <i> instead of <icon>

---

layouts/_default/index.html
layouts/_default/single.html

This is a simple PR that does not change the theme's behaviour for existing users in any way (the example page renders exactly the same).
On the other hand, it adds the flexibility of reusing the scrolling `index.html` template in multiple pages (not just the homepage) in a very simple way:
- create `subdir` directory with a `subdir/_index.md` file (i.e. a hugo section)
- Add `layout: index` in `subdir/_index.md` to instruct hugo to use the `_default/index.html` template.
- Place sections in `subdir/homepage/<section>.md` as usual
An example can be found in [this commit](https://github.com/chatziko/hugo-scroll/commit/59ded528e4e6bbfaca5747eb98e6a4b4330c9d5f) (not part of the PR).
The changes are straightforward:
- use a relative `./homepage` instead of `/homepage`
- Create a language menu …

Add flexibility to index.html to be used in subdirectories

---

exampleSite/config.toml
layouts/_default/index.html

The current process of generating scaled cover images is problematic, it produces upscaled blurry images on mobile resolutions. Here is a screenshot of the exampleSite on a 412x915 Galaxy Note 20: [screenshot-old](https://github.com/zjedi/hugo-scroll/assets/362089/ba8dbbcc-20ae-44b0-9a6d-7d158e94d03b).
The reason the cover appears blurry is that it uses the following 600x399 scaled version: [cover-scaled-old](https://github.com/zjedi/hugo-scroll/assets/362089/9a7f1754-14ce-4e6c-b514-806befb7d75b), wrapped in a rule:
```
@media (max-width:600px) {
```
Although the image has larger width (600px) that the canvas (412px), its __height__ (399px) is much smaller than the canvas (915px), so the `background-size: cover` algorithm upscales the image to cover the height, leading to the blurry …

Improve automatic scaling of cover image (fixes blur in mobiles)

---

assets/css/responsiveness.scss

When clicking on a section link on small screens, the section will scroll behind the fixed top menu, which is particularly bad when the top menu is long and wraps in multiple lines.
This PR adds `scroll-margin-top` to compensate for that. Maybe some CSS wizardry could take into accont the exact height of the top menu, but 48px is the height of a single menu line with the default font, and looks ok also for multiple lines.

Skip the top menu when scrolling on small screens

---

layouts/partials/head.html
netlify.toml
theme.toml

```
WARN  deprecated: resources.ToCSS was deprecated in Hugo v0.128.0 and will be removed
in a future release. Use css.Sass instead.
```

Use css.Sass instead of resources.ToCSS

---

exampleSite/hugo.toml
layouts/partials/head.html

If true, it will e.g. change the title tag for the Legal page to 
`<title>Legal | Jane Doe - Nutrition Coach & Chef Consultant</title>`

Add combine_page_and_site_title option

---

layouts/_default/index.html
layouts/_default/single.html

#196 added the flexibility to index.html to be used in subdirectories.
Unfortunately this broke the language menu in multihost settings. Both functionalities are made to work now by checking the `hugo.IsMultihost` condition.
This makes the code somewhat harder to read, but at least ensures that the regression is fixed.
Fixes: #214

Fix language menu in multihost setting

---

layouts/_default/index.html

Fix for the missing language in the url to the detailed page.

Use relLangURL for detailed page path in navigation
